### ISSUE TITLE
getting ShellDynListProtocols.c:47:1: error: conflicting types how to fix thx

### ISSUE THREAD

**Issue by kocoman1** [topeterk/ShellDynListProtocols#1]
getting ShellDynListProtocols.c:47:1: error: conflicting types how to fix thx

**Comment by topeterk** [comment]
Hi, is this the whole error message, usually the compiler names the things that are conflicting?
There should not be any other function with an incompatible prototype during compilation of the C file.

Are you trying to integrate this into the latest EDK2 source as they have changed a lot, maybe it is because of that?
Then maybe the code must be modified to fit into the latest code base.

I tried to replicated this issue but EDK2 requires pretty much _outdated_ toolchains that I haven't installed any more.
They should care a bit more of supporting latest compilers and update their documentations.
Nevertheless, because of that I cannot check it easily right now.

**Comment by topeterk** [comment]
I took this opportunity and had a look into Win11 on a fresh new virtual machine and tried it to reproduce it on this system.
With the EDKII sources from today and VS2019 with X64 build it ran quite well (just had to make a slight adjustment as an old compatibility header was removed in the meantime - Changes were pushed just minutes ago).

I guess you need to have a look for your self unless there a tons of variables I do not know from your system's state, the tooling and local changes to EDKII source that may interfere here.

**Comment by kocoman1** [comment]
what is autogen.h doing? I tried to remove something inside but its recreated right away when i build it

**Comment by topeterk** [comment]
This is an automatically generated file during the build by the EDK2 tools, see e.g. [EDK II Build Specification - AutoGen.h file](https://edk2-docs.gitbook.io/edk-ii-build-specification/8_pre-build_autogen_stage/83_auto-generated_code#8.3.6-autogen.h-file)
There should be no reason to edit this file, better to change the relevant global configurations, dsc settings or inf files accordingly.

**Comment by kocoman2** [comment]
ok I got it to work, I compared helloworld.c and yours and added the EFIAPI below the EFI_STATUS in line 47 of your c (on linux system, set x64 and gcc5)

**Comment by topeterk** [comment]
yes, you are right, according to [UEFI Shell Specification Version 2.2](http://www.uefi.org/sites/default/files/resources/UEFI_Shell_2_2.pdf) 3.11 _"UEFI Shell applications [...] have the same entry point (EFI_IMAGE_ENTRY_POINT) defined in section 4.1 of the UEFI specification"_.  
Looking at [the mentioned section](https://uefi.org/specs/UEFI/2.10/04_EFI_System_Table.html#efi-image-entry-point) the prototype ist defined as:  
```
typedef
EFI_STATUS
(EFIAPI *EFI_IMAGE_ENTRY_POINT) (
  IN EFI_HANDLE                  ImageHandle,
  IN EFI_SYSTEM_TABLE            *SystemTable
  );
```
Thanks for this hint, I'll fix this.
